---
  - name: install nginx
    action: apt name=nginx  update-cache=yes

  - name: write nginx.conf
    action: template src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx

  - name: delete default vhost
    action: file path=/etc/nginx/sites-enabled/default state=absent
    when: $delete_default_vhost
    notify:
      - restart nginx

  - name: add nginx "$name" vhost
    action: template src=vhost-www.j2 dest=/etc/nginx/sites-available/$name
    notify:
      - restart nginx

  - name: link nginx "$name" vhost in sites-enabled
    action: file src=/etc/nginx/sites-available/$name dest=/etc/nginx/sites-enabled/$name state=link
    notify:
      - restart nginx

  - name: Symlink clicker stats to local directory
    file: src=/vagrant/www dest=/var/www owner=vagrant group=vagrant state=link