---
  - hosts: all
    sudo: yes

    vars:
      delete_default_vhost: True
      user: www-data
      worker_processes: $ansible_processor_count
      pid: /var/run/nginx.pid
      listen: "*:80"
      name: dev
      server_name: dev
      worker_connections: 768

    tasks:
      - include: nginx/tasks/setup-nginx.yml

    handlers:
      - include: nginx/handlers/handlers.yml